import { colors } from "../theme/colors";
import { theme } from "../theme/tokens";

// Estilos de la pantalla de entrega/devolución. Viven aparte de
// DeliveryScreen.js — es la parte que menos tiene que ver con el flujo, y
// dejar el archivo solo con estado, cámara y checklist ayuda a leerlo.
export const styles = {
  light: { flex: 1, backgroundColor: colors.background },
  body: { padding: theme.spacing.screen, gap: theme.spacing.lg, paddingBottom: theme.spacing.xxl },
  centerBody: { padding: theme.spacing.xxl, alignItems: "center", gap: theme.spacing.lg },
  centerText: { alignItems: "center", gap: theme.spacing.sm },
  bigTitle: { ...theme.typography.title, color: colors.text, textAlign: "center" },
  bigSub: { fontSize: 15, color: colors.textMuted, lineHeight: 22, textAlign: "center" },
  successMark: { marginTop: theme.spacing.sm },
  markWarn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.warningBg,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.sm,
  },
  perfilFoto: { width: 96, height: 96, borderRadius: 48, alignSelf: "center" },
  cardTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
  infoRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: theme.spacing.md },
  infoLabel: { fontSize: 14, color: colors.textMuted },
  infoValue: { fontSize: 14, color: colors.text, fontWeight: "500", flexShrink: 1, textAlign: "right" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  divider: { height: 1, backgroundColor: colors.border },
  help: { fontSize: 14, color: colors.textMuted, lineHeight: 20 },
  okRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: colors.accent100,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: theme.radius.pill,
  },
  okRowText: { fontSize: 13, fontWeight: "700", color: colors.accentDark },
  input: {
    minHeight: theme.control.height,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: theme.radius.field,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: colors.text,
  },
  textarea: { minHeight: 90, textAlignVertical: "top" },
  noticeTeal: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    backgroundColor: colors.primary100,
    borderRadius: theme.radius.field,
    padding: theme.spacing.lg,
  },
  noticeTealText: { flex: 1, fontSize: 14, lineHeight: 20, color: colors.primary },
  noticeWarn: {
    flexDirection: "row",
    gap: theme.spacing.sm,
    backgroundColor: colors.warningBg,
    borderWidth: 1,
    borderColor: colors.warningBorder,
    borderRadius: theme.radius.field,
    padding: theme.spacing.lg,
  },
  noticeWarnText: { flex: 1, fontSize: 14, lineHeight: 20, color: colors.warningText },
  noticeWarnBox: {
    width: "100%",
    backgroundColor: colors.warningBg,
    borderWidth: 1,
    borderColor: colors.warningBorder,
    borderRadius: theme.radius.field,
    padding: theme.spacing.lg,
    gap: 4,
  },
  noticeWarnTitle: { fontSize: 14, fontWeight: "700", color: colors.warningText },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.md },
  gridCard: {
    width: "47%",
    borderRadius: theme.radius.field,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  gridThumb: { height: 84, width: "100%", backgroundColor: colors.surfaceSecondary },
  gridFoot: { padding: theme.spacing.sm, flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 6 },
  gridName: { fontSize: 13, color: colors.text, flex: 1 },
  gridCardSm: {
    width: "22%",
    aspectRatio: 1,
    borderRadius: theme.radius.sm,
    overflow: "hidden",
    backgroundColor: colors.surfaceSecondary,
  },
  gridThumbSm: { width: "100%", height: "100%" },
  deltaLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  deltaLabel: { fontSize: 14, color: colors.textMuted },
  deltaVal: { fontSize: 14, fontWeight: "600", color: colors.text },
  kmRow: {
    height: theme.control.height,
    borderWidth: 1.5,
    borderColor: colors.primary200,
    borderRadius: theme.radius.field,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: theme.spacing.sm,
  },
  kmInput: { flex: 1, fontSize: 18, fontWeight: "700", color: colors.text },
  kmSuffix: { fontSize: 16, color: colors.textMuted, fontWeight: "500" },
  fuelRow: { flexDirection: "row", gap: 6 },
  fuelBtn: {
    flex: 1,
    height: 58,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: theme.radius.field,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  fuelBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  fuelText: { fontSize: 16, fontWeight: "600", color: colors.textMuted },
  fuelSub: { fontSize: 10, color: colors.textMuted },
  faceCam: {
    height: 230,
    backgroundColor: colors.primary800,
    borderRadius: theme.radius.card,
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
  },
  faceCircle: {
    width: 104,
    height: 104,
    borderRadius: 52,
    borderWidth: 2,
    borderColor: "rgba(146,227,203,0.7)",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary900,
    overflow: "hidden",
  },
  faceCircleFoto: { width: "100%", height: "100%" },
  faceTitle: { fontSize: 16, fontWeight: "600", color: "#FFFFFF" },
  faceDesc: { fontSize: 13, color: colors.accent300, textAlign: "center", maxWidth: 240, lineHeight: 18 },
  liqMonto: { fontSize: 16, fontWeight: "800", color: colors.text },
  footNote: { fontSize: 12, color: colors.textMuted, textAlign: "center" },
  footNoteLeft: {
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 17,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: theme.spacing.sm,
  },
  ratingTitle: { fontSize: 15, fontWeight: "600", color: colors.text, textAlign: "center" },
  ratingSent: { fontSize: 14, fontWeight: "600", color: colors.success },
  stars: { flexDirection: "row", gap: 6 },
  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm },
  footer: {
    paddingHorizontal: theme.spacing.screen,
    paddingTop: theme.spacing.md,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: theme.spacing.sm,
  },

  // ---- barra de 3 pasos (devolución) ----
  stepWrap: {
    paddingHorizontal: theme.spacing.screen,
    paddingTop: theme.spacing.sm,
    paddingBottom: theme.spacing.md,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 6,
  },
  stepSegs: { flexDirection: "row", gap: 5 },
  stepSeg: { flex: 1, height: 4, borderRadius: 999, backgroundColor: colors.border },
  stepSegDone: { backgroundColor: colors.primary },
  stepSegNow: { backgroundColor: colors.accent },
  stepLabels: { flexDirection: "row", justifyContent: "space-between" },
  stepLbl: { fontSize: 11, fontWeight: "600", color: colors.textPlaceholder, flex: 1, textAlign: "center" },
  stepLblNow: { color: colors.primary },
  stepLblDone: { color: colors.accentDark },

  // ---- cámara (chrome claro translúcido) ----
  camContainer: { flex: 1, backgroundColor: colors.background },
  camTop: {
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
    gap: theme.spacing.md,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  camHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  camTitle: { fontSize: 15, fontWeight: "700", color: colors.text, flex: 1, marginHorizontal: theme.spacing.md },
  camFraction: { fontSize: 14, color: colors.primary, fontWeight: "700" },
  camBars: { flexDirection: "row", gap: 5 },
  camBar: { flex: 1, height: 4, borderRadius: 999 },
  barDone: { backgroundColor: colors.accent },
  barActive: { backgroundColor: colors.primary },
  barPending: { backgroundColor: colors.border },
  anglePills: { flexDirection: "row", gap: theme.spacing.sm, paddingVertical: 2 },
  anglePill: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: theme.radius.pill, backgroundColor: colors.surfaceSecondary },
  pillPast: { backgroundColor: colors.accent100 },
  pillCurr: { backgroundColor: colors.primary },
  pillFuture: { backgroundColor: colors.surfaceSecondary },
  pillText: { fontSize: 13 },
  viewfinder: {
    flex: 1,
    backgroundColor: colors.surfaceSecondary,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  guideBox: {
    position: "absolute",
    top: 24,
    bottom: 24,
    left: 20,
    right: 20,
    borderWidth: 2,
    borderColor: colors.primary300,
    borderStyle: "dashed",
    borderRadius: theme.radius.card,
  },
  vfBadge: {
    position: "absolute",
    top: 22,
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: theme.radius.field,
    borderWidth: 1,
    borderColor: colors.border,
  },
  vfBadgeText: { color: colors.text, fontSize: 15, fontWeight: "600" },
  zoomRow: {
    position: "absolute",
    bottom: 14,
    alignSelf: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "rgba(6,30,31,0.55)",
    borderRadius: theme.radius.pill,
    padding: 4,
  },
  zoomChip: {
    width: 36,
    height: 36,
    borderRadius: theme.radius.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  zoomChipActivo: { backgroundColor: colors.accent500 },
  zoomChipText: { color: "#FFFFFF", fontSize: 12.5, fontWeight: "700" },
  zoomChipTextActivo: { color: colors.text },
  camShutter: {
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: theme.spacing.md,
  },
  shutterRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  skipText: { fontSize: 13, fontWeight: "700", color: colors.accentDark },
  galleryBtn: {
    width: 52,
    height: 52,
    borderRadius: theme.radius.field,
    backgroundColor: colors.primary100,
    borderWidth: 1.5,
    borderColor: colors.primary200,
    alignItems: "center",
    justifyContent: "center",
  },
  shutterBtn: { width: 72, height: 72, borderRadius: 36, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" },
  shutterInner: { width: 60, height: 60, borderRadius: 30, borderWidth: 3, borderColor: "#FFFFFF" },
  thumbCounter: {
    width: 52,
    height: 52,
    borderRadius: theme.radius.field,
    backgroundColor: colors.accent100,
    alignItems: "center",
    justifyContent: "center",
  },
  thumbCounterText: { fontSize: 14, fontWeight: "800", color: colors.accentDark },
  camNote: { fontSize: 13, color: colors.textMuted, textAlign: "center" },
  camPermBox: {
    padding: theme.spacing.xl,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: theme.radius.card,
    marginHorizontal: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  camPermTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  camPermDesc: {
    fontSize: 13,
    color: colors.textMuted,
    textAlign: "center",
    lineHeight: 18,
  },
  camPermBtn: {
    marginTop: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: theme.radius.field,
  },
  camPermBtnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },

  // ---- Tarjeta de Peritaje Asistido por IA ----
  aiCard: {
    gap: 8,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.surface,
  },
  aiHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  aiTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  aiLoadingText: {
    fontSize: 13,
    color: colors.textMuted,
    fontStyle: "italic",
    paddingVertical: 4,
  },
  aiSubtitle: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
  },
  aiBars: {
    gap: 6,
    paddingVertical: 2,
  },
  aiBarRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiBarLabel: {
    width: 68,
    fontSize: 12,
    color: colors.text,
    fontWeight: "500",
  },
  aiBarTrack: {
    flex: 1,
    height: 8,
    backgroundColor: colors.surfaceSecondary || "#F1F5F9",
    borderRadius: 4,
    overflow: "hidden",
  },
  aiBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  aiBarPct: {
    width: 36,
    fontSize: 12,
    fontWeight: "600",
    color: colors.text,
    textAlign: "right",
  },
  aiDiagnosis: {
    fontSize: 12.5,
    color: colors.textMuted,
    lineHeight: 18,
    marginTop: 2,
  },
};