"""baseline_esquema_inicial

Revision ID: c1d400bb56cd
Revises: 
Create Date: 2026-09-14 22:40:40.963361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificador de esta revisión (actualizar a mano o con `alembic revision`).
revision: str = 'c1d400bb56cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio_cobertura_km', sa.Float(), nullable=True),
    sa.Column('managers_asignados', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('foto_perfil_verificada_url', sa.String(), nullable=True),
    sa.Column('foto_perfil_url', sa.String(), nullable=True),
    sa.Column('estado_documentos', sa.String(), nullable=True),
    sa.Column('confianza_ocr', sa.Float(), nullable=True),
    sa.Column('notas_auditoria', sa.Text(), nullable=True),
    sa.Column('verificacion_externa_estado', sa.String(), nullable=True),
    sa.Column('verificacion_externa_ref', sa.String(), nullable=True),
    sa.Column('verificacion_externa_actualizada', sa.DateTime(), nullable=True),
    sa.Column('metodo_verificacion', sa.String(), nullable=True),
    sa.Column('antecedentes_estado', sa.String(), nullable=True),
    sa.Column('roles_activos', sa.JSON(), nullable=True),
    sa.Column('suspendido', sa.Boolean(), nullable=True),
    sa.Column('eliminacion_solicitada_en', sa.DateTime(), nullable=True),
    sa.Column('sucursal_id', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('cuenta_bancaria', sa.JSON(), nullable=True),
    sa.Column('expo_push_token', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('pais_documento', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('licencia_pais_emisor', sa.String(), nullable=True),
    sa.Column('licencia_numero', sa.String(), nullable=True),
    sa.Column('licencia_clase', sa.String(), nullable=True),
    sa.Column('licencia_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('licencia_estado', sa.String(), nullable=True),
    sa.Column('carnet_frontal_url', sa.String(), nullable=True),
    sa.Column('carnet_trasero_url', sa.String(), nullable=True),
    sa.Column('licencia_url', sa.String(), nullable=True),
    sa.Column('pic_url', sa.String(), nullable=True),
    sa.Column('pic_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('es_residente_chile', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio_residencia', sa.DateTime(), nullable=True),
    sa.Column('tarjeta_token', sa.String(), nullable=True),
    sa.Column('tarjeta_ultimos4', sa.String(), nullable=True),
    sa.Column('tarjeta_marca', sa.String(), nullable=True),
    sa.Column('tarjeta_estado', sa.String(), nullable=True),
    sa.Column('tarjeta_titular', sa.String(), nullable=True),
    sa.Column('mp_customer_id', sa.String(), nullable=True),
    sa.Column('codigo_referido', sa.String(), nullable=True),
    sa.Column('referido_por_id', sa.String(), nullable=True),
    sa.Column('bono_referido_activado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_numero_documento'), 'usuarios', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_usuarios_rut'), 'usuarios', ['rut'], unique=True)
    op.create_index(op.f('ix_usuarios_verificacion_externa_ref'), 'usuarios', ['verificacion_externa_ref'], unique=False)
    op.create_table('autos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dueno_id', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(), nullable=False),
    sa.Column('tarifa_dia', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('ubicacion_base', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('equipamiento', sa.JSON(), nullable=True),
    sa.Column('transmision', sa.String(), nullable=True),
    sa.Column('combustible', sa.String(), nullable=True),
    sa.Column('asientos', sa.Integer(), nullable=True),
    sa.Column('puertas', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('doc_inscripcion_url', sa.String(), nullable=True),
    sa.Column('doc_permiso_circulacion_url', sa.String(), nullable=True),
    sa.Column('doc_soap_url', sa.String(), nullable=True),
    sa.Column('doc_revision_tecnica_url', sa.String(), nullable=True),
    sa.Column('doc_seguro_url', sa.String(), nullable=True),
    sa.Column('documentos_verificados', sa.Boolean(), nullable=True),
    sa.Column('gps_consentimiento', sa.Boolean(), nullable=True),
    sa.Column('gps_consentimiento_fecha', sa.DateTime(), nullable=True),
    sa.Column('gps_proveedor', sa.String(), nullable=True),
    sa.Column('gps_device_id', sa.String(), nullable=True),
    sa.Column('gps_instalado', sa.Boolean(), nullable=True),
    sa.Column('gps_ultima_posicion', sa.JSON(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autos_patente'), 'autos', ['patente'], unique=True)
    op.create_table('configuracion_plataforma',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('valor_uf_clp', sa.Float(), nullable=True),
    sa.Column('comision_plataforma_pct', sa.Float(), nullable=True),
    sa.Column('hold_enrolamiento_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_limpieza_estandar_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_limpieza_profunda_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_combustible_cuarto_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_km_extra_clp', sa.Integer(), nullable=True),
    sa.Column('km_diarios_incluidos', sa.Integer(), nullable=True),
    sa.Column('periodo_gracia_minutos', sa.Integer(), nullable=True),
    sa.Column('dias_cobro_posterior_peajes', sa.Integer(), nullable=True),
    sa.Column('edad_minima_arriendo', sa.Integer(), nullable=True),
    sa.Column('bono_invitado_pct_t1', sa.Float(), nullable=True),
    sa.Column('bono_invitado_pct_t2', sa.Float(), nullable=True),
    sa.Column('bono_invitado_pct_t3', sa.Float(), nullable=True),
    sa.Column('bono_invitado_dias_t1', sa.Integer(), nullable=True),
    sa.Column('bono_invitado_dias_t2', sa.Integer(), nullable=True),
    sa.Column('bono_invitado_dias_t3', sa.Integer(), nullable=True),
    sa.Column('bono_referente_pct_t1', sa.Float(), nullable=True),
    sa.Column('bono_referente_pct_t2', sa.Float(), nullable=True),
    sa.Column('bono_referente_dias_t1', sa.Integer(), nullable=True),
    sa.Column('bono_referente_dias_t2', sa.Integer(), nullable=True),
    sa.Column('tarifas_categoria', sa.JSON(), nullable=True),
    sa.Column('garantia_categoria_clp', sa.JSON(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_por_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_cobro',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('tipo_cuenta', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('titular', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('predeterminada', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_cobro_usuario_id'), 'cuentas_cobro', ['usuario_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('entidad_tipo', sa.String(), nullable=True),
    sa.Column('entidad_id', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_creado_en'), 'notificaciones', ['creado_en'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('tarjetas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('mp_customer_id', sa.String(), nullable=True),
    sa.Column('mp_card_id', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('ultimos4', sa.String(), nullable=True),
    sa.Column('vencimiento', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('titular', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('predeterminada_cobro', sa.Boolean(), nullable=True),
    sa.Column('predeterminada_garantia', sa.Boolean(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarjetas_usuario_id'), 'tarjetas', ['usuario_id'], unique=False)
    op.create_table('bloqueos_calendario_auto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auto_id', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('auto_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'auto_id', name='uq_favorito_usuario_auto')
    )
    op.create_index(op.f('ix_favoritos_auto_id'), 'favoritos', ['auto_id'], unique=False)
    op.create_index(op.f('ix_favoritos_usuario_id'), 'favoritos', ['usuario_id'], unique=False)
    op.create_table('mantenciones_auto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auto_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auto_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('monto_cobro', sa.Integer(), nullable=True),
    sa.Column('monto_hold', sa.Integer(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.Column('tarjeta_cobro_id', sa.String(), nullable=True),
    sa.Column('tarjeta_garantia_id', sa.String(), nullable=True),
    sa.Column('cargo_limpieza_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_combustible_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_km_extra_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_atraso_clp', sa.Integer(), nullable=True),
    sa.Column('cargos_adicionales_clp', sa.Integer(), nullable=True),
    sa.Column('cargo_falta_grave_clp', sa.Integer(), nullable=True),
    sa.Column('monto_cobro_final', sa.Integer(), nullable=True),
    sa.Column('liquidacion_dueno_clp', sa.Integer(), nullable=True),
    sa.Column('codigo_qr_hash', sa.String(), nullable=True),
    sa.Column('codigo_qr_expira_en', sa.DateTime(), nullable=True),
    sa.Column('lugar_entrega_acordado', sa.String(), nullable=False),
    sa.Column('contrato_pdf_url', sa.String(), nullable=True),
    sa.Column('hash_contrato_sha256', sa.String(length=64), nullable=True),
    sa.Column('fecha_firma_biometrica', sa.DateTime(), nullable=True),
    sa.Column('precheck_cliente_confirmado', sa.Boolean(), nullable=True),
    sa.Column('precheck_cliente_timestamp', sa.DateTime(), nullable=True),
    sa.Column('precheck_dueno_confirmado', sa.Boolean(), nullable=True),
    sa.Column('precheck_dueno_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recordatorio_entrega_24h_enviado', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_entrega_2h_enviado', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_devolucion_24h_enviado', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_devolucion_2h_enviado', sa.Boolean(), nullable=True),
    sa.Column('gps_alerta_30m_enviada', sa.Boolean(), nullable=True),
    sa.Column('gps_alerta_60m_enviada', sa.Boolean(), nullable=True),
    sa.Column('motivo_multas', sa.Text(), nullable=True),
    sa.Column('multas_detalle', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_cobro_id'], ['tarjetas.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_garantia_id'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_auto_id'), 'reservas', ['auto_id'], unique=False)
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_reservas_codigo_qr_hash'), 'reservas', ['codigo_qr_hash'], unique=False)
    op.create_index(op.f('ix_reservas_estado'), 'reservas', ['estado'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('autor_id', sa.String(), nullable=False),
    sa.Column('autor_rol', sa.String(), nullable=False),
    sa.Column('destinatario_id', sa.String(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklists_auto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('nivel_combustible', sa.String(), nullable=False),
    sa.Column('estado_limpieza', sa.String(), nullable=True),
    sa.Column('cargo_limpieza_clp', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('firma_svg', sa.Text(), nullable=True),
    sa.Column('selfie_entrega_url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conductores_adicionales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('pais_documento', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('licencia_pais_emisor', sa.String(), nullable=True),
    sa.Column('licencia_numero', sa.String(), nullable=True),
    sa.Column('licencia_clase', sa.String(), nullable=True),
    sa.Column('licencia_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('pic_url', sa.String(), nullable=True),
    sa.Column('pic_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('es_residente_chile', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio_residencia', sa.DateTime(), nullable=True),
    sa.Column('carnet_frontal_url', sa.String(), nullable=True),
    sa.Column('carnet_trasero_url', sa.String(), nullable=True),
    sa.Column('licencia_url', sa.String(), nullable=True),
    sa.Column('selfie_url', sa.String(), nullable=True),
    sa.Column('estado_kyc', sa.String(), nullable=True),
    sa.Column('confianza_ocr', sa.Float(), nullable=True),
    sa.Column('notas_auditoria', sa.Text(), nullable=True),
    sa.Column('antecedentes_estado', sa.String(), nullable=True),
    sa.Column('verificacion_externa_ref', sa.String(), nullable=True),
    sa.Column('verificacion_externa_estado', sa.String(), nullable=True),
    sa.Column('verificacion_externa_actualizada', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conductores_adicionales_numero_documento'), 'conductores_adicionales', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_conductores_adicionales_reserva_id'), 'conductores_adicionales', ['reserva_id'], unique=True)
    op.create_index(op.f('ix_conductores_adicionales_rut'), 'conductores_adicionales', ['rut'], unique=False)
    op.create_index(op.f('ix_conductores_adicionales_verificacion_externa_ref'), 'conductores_adicionales', ['verificacion_externa_ref'], unique=False)
    op.create_table('disputas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('admin_asignado_id', sa.String(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('foto_evidencia_url', sa.String(), nullable=True),
    sa.Column('evidencia_fotos', sa.JSON(), nullable=True),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmas_contrato',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('firma_svg', sa.Text(), nullable=True),
    sa.Column('nombre_firmante', sa.String(), nullable=True),
    sa.Column('hash_contrato_sha256', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('firmado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', 'rol', name='uq_firma_contrato_reserva_rol')
    )
    op.create_index(op.f('ix_firmas_contrato_reserva_id'), 'firmas_contrato', ['reserva_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('autor_id', sa.String(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('referencia_pago', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('liquidado_en', sa.DateTime(), nullable=True),
    sa.Column('intentos_liquidacion', sa.Integer(), nullable=True),
    sa.Column('procesando_desde', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_estado'), 'pagos', ['estado'], unique=False)
    op.create_index(op.f('ix_pagos_reserva_id'), 'pagos', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_pagos_tipo'), 'pagos', ['tipo'], unique=False)
    op.create_index(op.f('ix_pagos_usuario_id'), 'pagos', ['usuario_id'], unique=False)
    op.create_table('verificaciones_entrega',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reserva_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('foto_evidencia_url', sa.String(), nullable=True),
    sa.Column('motivo_rechazo', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('dueno_id_que_verifica', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dueno_id_que_verifica'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets_soporte',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('sucursal_id', sa.String(), nullable=True),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('escalado_a_disputa', sa.Boolean(), nullable=True),
    sa.Column('disputa_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disputa_id'], ['disputas.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_soporte')
    op.drop_table('verificaciones_entrega')
    op.drop_index(op.f('ix_pagos_usuario_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_tipo'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_reserva_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_estado'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_firmas_contrato_reserva_id'), table_name='firmas_contrato')
    op.drop_table('firmas_contrato')
    op.drop_table('disputas')
    op.drop_index(op.f('ix_conductores_adicionales_verificacion_externa_ref'), table_name='conductores_adicionales')
    op.drop_index(op.f('ix_conductores_adicionales_rut'), table_name='conductores_adicionales')
    op.drop_index(op.f('ix_conductores_adicionales_reserva_id'), table_name='conductores_adicionales')
    op.drop_index(op.f('ix_conductores_adicionales_numero_documento'), table_name='conductores_adicionales')
    op.drop_table('conductores_adicionales')
    op.drop_table('checklists_auto')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_reservas_estado'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_codigo_qr_hash'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_auto_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_table('mantenciones_auto')
    op.drop_index(op.f('ix_favoritos_usuario_id'), table_name='favoritos')
    op.drop_index(op.f('ix_favoritos_auto_id'), table_name='favoritos')
    op.drop_table('favoritos')
    op.drop_table('bloqueos_calendario_auto')
    op.drop_index(op.f('ix_tarjetas_usuario_id'), table_name='tarjetas')
    op.drop_table('tarjetas')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_creado_en'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_cuentas_cobro_usuario_id'), table_name='cuentas_cobro')
    op.drop_table('cuentas_cobro')
    op.drop_table('configuracion_plataforma')
    op.drop_index(op.f('ix_autos_patente'), table_name='autos')
    op.drop_table('autos')
    op.drop_index(op.f('ix_usuarios_verificacion_externa_ref'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_rut'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_numero_documento'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('sucursales')
    # ### end Alembic commands ###